version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs
      - ./dhparam.pem:/etc/nginx/dhparam.pem:ro
    networks:
      - rayan

networks:
  rayan:
    external: true