version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/front.mohammadnasiroleslami.ir:/etc/nginx/certs/front:ro  # Volume for front certificate
      - /etc/letsencrypt/live/back.mohammadnasiroleslami.ir:/etc/nginx/certs/back:ro    # Volume for back certificate
      - ./dhparam.pem:/etc/nginx/dhparam.pem:ro
    networks:
      - rayan

networks:
  rayan:
    external: true
